Attribute VB_Name = "Init"
Option Explicit
Public Sub Initialize()
    Set WB_BILLING_DATA_TOOL = ThisWorkbook
    Set WS_TTEXTRACT = WB_BILLING_DATA_TOOL.Sheets(SHT_TTEXTRACT)
    Set WS_RDEXTACT = WB_BILLING_DATA_TOOL.Sheets(SHT_RDEXTACT)
    Set WS_UPDEXTRACT = WB_BILLING_DATA_TOOL.Sheets(SHT_UPDEXTRACT)
    Set WS_PLCREATION = WB_BILLING_DATA_TOOL.Sheets(SHT_PLCREATION)
    'Set WS_CONSOLIDATION_MASTER = WB_BILLING_DATA_TOOL.Sheets(SHT_CONSOLIDATION_MASTER)
End Sub

